# Generated by Django 3.2.5 on 2021-08-10 03:03

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]
